language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
dist: xenial
addons:
  apt:
    packages:
      - libsodium18
      - graphviz
      - bind9
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
script: python -m unittest tests/script_tests.py
